namespace PolyPlane.Net
{
    public enum PacketTypes
    {
        PlaneUpdate,
        PlaneStatusList,
        PlaneStatus,
        PlaneListUpdate,
        MissileUpdateList,
        MissileUpdate,
        MissileList,
        Impact,
        NewPlayer,
        NewBullet,
        NewMissile,
        NewDecoy,
        SetID,
        ChatMessage,
        GetOtherPlanes,
        ExpiredObjects,
        PlayerDisconnect,
        PlayerReset,
        SyncResponse,
        SyncRequest,
        Discovery,
        KickPlayer,
        ImpactList,
        BulletList,
        DecoyList,
        PlayerEvent,
        ScoreEvent,
        GameStateUpdate
    }
}
